from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start2{CMD_INDEX}'
        self.MirrorCommand = f'dl2{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzip2{CMD_INDEX}'
        self.ZipMirrorCommand = f'zip2{CMD_INDEX}'
        self.CancelMirror = f'batal2{CMD_INDEX}'
        self.CancelAllCommand = f'batalin2{CMD_INDEX}'
        self.ListCommand = f'list2{CMD_INDEX}'
        self.SearchCommand = f'cari2{CMD_INDEX}'
        self.StatusCommand = f'status2{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users2{CMD_INDEX}'
        self.AuthorizeCommand = f'auth2{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauth2{CMD_INDEX}'
        self.AddSudoCommand = f'addsudo2{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudo2{CMD_INDEX}'
        self.PingCommand = f'ping2{CMD_INDEX}'
        self.RestartCommand = f'restart2{CMD_INDEX}'
        self.StatsCommand = f'stats2{CMD_INDEX}'
        self.HelpCommand = f'bantuan2{CMD_INDEX}'
        self.LogCommand = f'log2{CMD_INDEX}'
        self.CloneCommand = f'salin2{CMD_INDEX}'
        self.CountCommand = f'hitung2{CMD_INDEX}'
        self.WatchCommand = f'watch2{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwatch2{CMD_INDEX}'
        self.QbMirrorCommand = f'qb2{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzip2{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzip2{CMD_INDEX}'
        self.DeleteCommand = f'del2{CMD_INDEX}'
        self.ShellCommand = f'shell2{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp2{CMD_INDEX}'
        self.LeechSetCommand = f'leechset2{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb2{CMD_INDEX}'
        self.LeechCommand = f'leech2{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipleech2{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleech2{CMD_INDEX}'
        self.QbLeechCommand = f'qbleech2{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunzipleech2{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleech2{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwatch2{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipwatch2{CMD_INDEX}'
        self.QbSelectCommand = f'qbsel2{CMD_INDEX}'
        self.RssListCommand = f'rsslist2{CMD_INDEX}'
        self.RssGetCommand = f'rssget2{CMD_INDEX}'
        self.RssSubCommand = f'rsssub2{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub2{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset2{CMD_INDEX}'
        self.EvalCommand = f'eval2{CMD_INDEX}'
        self.ExecCommand = f'exec2{CMD_INDEX}'
        self.ClearLocalsCommand = f'clearlocals2{CMD_INDEX}'

BotCommands = _BotCommands()
