from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start3{CMD_INDEX}'
        self.MirrorCommand = f'dl3{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzip3{CMD_INDEX}'
        self.ZipMirrorCommand = f'zip3{CMD_INDEX}'
        self.CancelMirror = f'batal3{CMD_INDEX}'
        self.CancelAllCommand = f'batalin3{CMD_INDEX}'
        self.ListCommand = f'list3{CMD_INDEX}'
        self.SearchCommand = f'cari3{CMD_INDEX}'
        self.StatusCommand = f'status3{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users3{CMD_INDEX}'
        self.AuthorizeCommand = f'auth3{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauth3{CMD_INDEX}'
        self.AddSudoCommand = f'addsudo3{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudo3{CMD_INDEX}'
        self.PingCommand = f'ping3{CMD_INDEX}'
        self.RestartCommand = f'restart3{CMD_INDEX}'
        self.StatsCommand = f'stats3{CMD_INDEX}'
        self.HelpCommand = f'bantuan3{CMD_INDEX}'
        self.LogCommand = f'log3{CMD_INDEX}'
        self.CloneCommand = f'salin3{CMD_INDEX}'
        self.CountCommand = f'hitung3{CMD_INDEX}'
        self.WatchCommand = f'watch3{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwatch3{CMD_INDEX}'
        self.QbMirrorCommand = f'qb3{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzip3{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzip3{CMD_INDEX}'
        self.DeleteCommand = f'del3{CMD_INDEX}'
        self.ShellCommand = f'shell3{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp3{CMD_INDEX}'
        self.LeechSetCommand = f'leechset3{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb3{CMD_INDEX}'
        self.LeechCommand = f'leech3{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipleech3{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleech3{CMD_INDEX}'
        self.QbLeechCommand = f'qbleech3{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunzipleech3{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleech3{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwatch3{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipwatch3{CMD_INDEX}'
        self.QbSelectCommand = f'qbsel3{CMD_INDEX}'
        self.RssListCommand = f'rsslist3{CMD_INDEX}'
        self.RssGetCommand = f'rssget3{CMD_INDEX}'
        self.RssSubCommand = f'rsssub3{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub3{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset3{CMD_INDEX}'
        self.EvalCommand = f'eval3{CMD_INDEX}'
        self.ExecCommand = f'exec3{CMD_INDEX}'
        self.ClearLocalsCommand = f'clearlocals3{CMD_INDEX}'

BotCommands = _BotCommands()
